package com.asbitech.client_ms.events;

import com.asbitech.common.domain.EventType;

public enum PrincipalEvent implements EventType {
    PRINCIPAL_CREATED,
    PRINCIPAL_UPDATED,
    PRINCIPAL_DELETED,
    PRINCIPAL_ACTIVATED,
    PRINCIPAL_DEACTIVATED,
    PRINCIPAL_RESTORED,
    PRINCIPAL_SUSPENDED,
    PRINCIPAL_UNSUSPENDED,
    PRINCIPAL_LOCKED,
    PRINCIPAL_UNLOCKED,
    PRINCIPAL_PASSWORD_CHANGED,
    PRINCIPAL_EMAIL_VERIFIED,
    PRINCIPAL_PHONE_VERIFIED,
    PRINCIPAL_CREATION_FAILED,
    ACCOUNT_ACTIVATED,
    ACCOUNT_ACTIVATION_FAILED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    MFA_ACTIVATION_INITIATED,
    MFA_ACTIVATION_INIT_FAILED,
    MFA_ACTIVATION_FAILED,
    MFA_ACTIVATED,
    PROFILE_UPDATED,
    PROFILE_UPDATE_FAILED;
}
